# Generated by Django 5.2.7 on 2025-11-09 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(max_length=30, unique=True, verbose_name='Лоін')),
                ('email', models.CharField(unique=True, verbose_name='Електронна пошта')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Номер телефону')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Прізвище')),
                ('birth_date', models.DateField(blank=True, verbose_name='Дата народження')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_image/', verbose_name='Фото')),
                ('date_registration', models.DateTimeField(default=datetime.datetime(2025, 11, 9, 12, 16, 53, 974436, tzinfo=datetime.timezone.utc), verbose_name='Дата реєстрації')),
                ('date_update', models.DateTimeField(default=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 12, 16, 53, 974436, tzinfo=datetime.timezone.utc), verbose_name='Дата реєстрації'), verbose_name='Дата оновлення')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
        ),
    ]
