# Generated by Django 5.2.7 on 2025-11-09 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usermodel_date_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 12, 43, 5, 830268, tzinfo=datetime.timezone.utc), verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_update',
            field=models.DateTimeField(default=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 12, 43, 5, 830268, tzinfo=datetime.timezone.utc), verbose_name='Дата реєстрації'), verbose_name='Дата оновлення'),
        ),
    ]
