# Generated by Django 5.2.7 on 2025-11-09 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usermodel_date_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='date_update',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 12, 47, 18, 614775, tzinfo=datetime.timezone.utc), verbose_name='Дата реєстрації'),
        ),
    ]
