# Generated by Django 5.2.7 on 2025-11-09 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_usermodel_date_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 12, 48, 46, 356500, tzinfo=datetime.timezone.utc), verbose_name='Дата реєстрації'),
        ),
    ]
