# Generated by Django 5.2.7 on 2025-11-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_usermodel_date_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='date_registration',
        ),
    ]
