# Generated by Django 5.2.7 on 2025-11-09 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_usermodel_date_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='login',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 12, 57, 52, 735334, tzinfo=datetime.timezone.utc), verbose_name='Дата реєстрації'),
        ),
    ]
