# Generated by Django 5.2.7 on 2025-11-09 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_usermodel_login_usermodel_date_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 13, 3, 0, 68305, tzinfo=datetime.timezone.utc), verbose_name='Дата реєстрації'),
        ),
    ]
