# Generated by Django 5.2.7 on 2025-11-09 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_usermodel_is_active_usermodel_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 13, 4, 6, 946385, tzinfo=datetime.timezone.utc), verbose_name='Дата реєстрації'),
        ),
    ]
