# Generated by Django 5.2.7 on 2025-10-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=55)),
                ('course_description', models.TextField(max_length=155)),
                ('course_tag', models.CharField(max_length=10)),
            ],
        ),
    ]
