# Generated by Django 5.2.7 on 2025-10-15 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
        ('members_app', '0002_alter_membersmodel_members_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesmodel',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members_app.membersmodel'),
        ),
        migrations.AlterField(
            model_name='coursesmodel',
            name='course_name',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
