# Generated by Django 5.2.7 on 2025-10-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_coursesmodel_member_alter_coursesmodel_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesmodel',
            name='member',
        ),
    ]
