# Generated by Django 5.2.7 on 2025-10-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_remove_coursesmodel_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesmodel',
            old_name='course_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='coursesmodel',
            old_name='course_tag',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='coursesmodel',
            old_name='course_name',
            new_name='title',
        ),
    ]
