# Generated by Django 5.2.7 on 2025-10-16 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_rename_course_description_coursesmodel_description_and_more'),
        ('members_app', '0009_remove_membersmodel_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesmodel',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members_app.membersmodel'),
        ),
        migrations.AlterField(
            model_name='coursesmodel',
            name='tag',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
