# Generated by Django 5.2.7 on 2025-10-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0005_coursesmodel_member_alter_coursesmodel_tag'),
        ('members_app', '0010_membersmodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesmodel',
            name='member',
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='member',
            field=models.ManyToManyField(related_name='courses', to='members_app.membersmodel'),
        ),
    ]
