# Generated by Django 5.2.7 on 2025-10-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_firstname', models.CharField(max_length=25)),
                ('members_lastname', models.CharField(max_length=25)),
                ('members_age', models.IntegerField()),
                ('members_sex', models.CharField(max_length=6)),
            ],
        ),
    ]
