# Generated by Django 5.2.7 on 2025-10-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersmodel',
            name='members_age',
            field=models.IntegerField(),
        ),
    ]
