# Generated by Django 5.2.7 on 2025-10-15 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_remove_coursesmodel_member'),
        ('members_app', '0002_alter_membersmodel_members_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersmodel',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses_app.coursesmodel'),
        ),
    ]
