# Generated by Django 5.2.7 on 2025-10-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0003_membersmodel_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='membersmodel',
            name='members_sex',
        ),
    ]
