# Generated by Django 5.2.7 on 2025-10-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0004_membersex_remove_membersmodel_members_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersmodel',
            name='members_sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members_app.membersex'),
        ),
    ]
