# Generated by Django 5.2.7 on 2025-10-16 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_remove_coursesmodel_member'),
        ('members_app', '0005_membersmodel_members_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersmodel',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses_app.coursesmodel'),
        ),
        migrations.AlterField(
            model_name='membersmodel',
            name='members_sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members_app.membersex'),
        ),
    ]
