# Generated by Django 5.2.7 on 2025-10-16 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0006_alter_membersmodel_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersmodel',
            name='members_sex',
            field=models.ForeignKey(default='Hidden', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members_app.membersex'),
        ),
    ]
