# Generated by Django 5.2.7 on 2025-10-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0007_alter_membersmodel_members_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membersmodel',
            old_name='members_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='membersmodel',
            old_name='member_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='membersmodel',
            old_name='members_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='membersmodel',
            old_name='members_sex',
            new_name='sex',
        ),
    ]
