# Generated by Django 5.2.7 on 2025-10-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0008_rename_members_age_membersmodel_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersmodel',
            name='course',
        ),
    ]
