# Generated by Django 5.2.7 on 2025-10-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0009_remove_membersmodel_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
