# Generated by Django 5.2.7 on 2025-10-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0010_membersmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersmodel',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('H', 'Hiddden')], default='H', null=True),
        ),
        migrations.DeleteModel(
            name='MemberSex',
        ),
    ]
